apiVersion: v1
kind: Service
metadata:
  name: python-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: python
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30008

    
